### ISSUE TITLE
Todo: Game Logic

### ISSUE THREAD

**Issue by druwan** [druwan/sinhalaquizapp#8]
As of now, all components are done. Left to do is add the actual logic of a quiz game

- [x] Create a game of 5 questions
- [x] Loop through after answering each one and connect to #6 
- [x] Keep track of score
